/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package theory;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author gravitys
 */
public class Table2 extends javax.swing.JFrame {
    
    /**
     * Creates new form Table2
     */
    private Data d;
    private JTable table;
    public Table2(Data d) {
        this.d = d;
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setBounds(100, 100, 485, 218);
        getContentPane().setLayout(null);
        String[][] data = new String[d.rule.size()][5];
        for(int i = 0;i<d.rule.size();i++){
            data[i][0] = d.rule.get(i);
            data[i][1] = d.channel1.get(i);
            data[i][2] = d.channel2.get(i);
            data[i][3] = d.channel1String.get(i);
            data[i][4] = d.channel2String.get(i);
        }
        String header[] = new String[5];
        header[0] = "To";
        header[1] = "Form 1";
        header[2] = "Form 2";
        header[3] = "String 1";
        header[4] = "String 2";
        // Table
        table = new JTable(data, header);

        table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        table.setRowHeight(40);
        for (int i = 0; i < d.rule.size(); i++) {
            try{table.getColumnModel().getColumn(i).setPreferredWidth(40);}catch(Exception e){System.out.println(e);}
        }
        JScrollPane scrollPane = new JScrollPane(table);

        scrollPane.setBounds(36, 37, 350, 300);
        getContentPane().add(scrollPane, BorderLayout.CENTER);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jButton1)
                .addContainerGap(239, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(337, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
