/*
 * Code By GravityS
 */
package theory;

import java.awt.BorderLayout;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class Table extends javax.swing.JFrame {

    private Algorithm a;
    private JTable table;
    private String acc;
    /**
     * Creates new form Table
     */
    public Table(Algorithm a) {
        this.a = a;
        String[][] ans = a.cal();
        if(a.c){
            acc = "Accept";
            //showConvert.setVisible(true);
        }else{
            acc = "Not Accept";
            //showConvert.setVisible(false);
        }
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setBounds(100, 100, 485, 218);
        getContentPane().setLayout(null);
        String[][] ansT = new String[ans.length - 1][ans.length - 1];
        for (int i = 1; i < ans.length; i++) {
            for (int j = 1; j < ans[i].length; j++) {
                ansT[i - 1][j - 1] = ans[i][j];
            }
        }
        String data[][] = ansT;
        String header[] = new String[ansT.length];
        for (int i = 0; i < ansT.length; i++) {
            header[i] = "" + a.str.charAt(i);
        }
        // Table
        table = new JTable(data, header);

        table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        table.setRowHeight(60);
        for (int i = 0; i < ansT.length; i++) {
            table.getColumnModel().getColumn(i).setPreferredWidth(60);
        }
        JScrollPane scrollPane = new JScrollPane(table);

        scrollPane.setBounds(36, 37, 500, 450);
        getContentPane().add(scrollPane, BorderLayout.CENTER);

        initComponents();
        if(a.c){
            showConvert.setVisible(true);
        }else{
            showConvert.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Check = new javax.swing.JButton();
        Close = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        showConvert = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Check.setText("Check");
        Check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckActionPerformed(evt);
            }
        });

        Close.setText("Close");
        Close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseActionPerformed(evt);
            }
        });

        jLabel1.setText(acc);
        jLabel1.setToolTipText("");

        showConvert.setText("Show Convert");
        showConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showConvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(Check)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel1)
                        .addContainerGap(269, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(showConvert)
                        .addGap(89, 89, 89)
                        .addComponent(Close)
                        .addGap(90, 90, 90))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 495, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Check)
                    .addComponent(Close)
                    .addComponent(showConvert))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckActionPerformed
        // TODO add your handling code here:
        int col = table.getSelectedColumn();
        int row = table.getSelectedRow();
        Data d = a.getInfo(String.valueOf(row+1) , String.valueOf(col+1));
        
        Table2 t = new Table2(d);
        t.setVisible(true);
    }//GEN-LAST:event_CheckActionPerformed

    private void CloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_CloseActionPerformed

    private void showConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showConvertActionPerformed
        // TODO add your handling code here:
        new ShowConvert(a).setVisible(true);
    }//GEN-LAST:event_showConvertActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Check;
    private javax.swing.JButton Close;
    javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton showConvert;
    // End of variables declaration//GEN-END:variables
}
